// Global Wrapper (navbar/footer live here) 
import type { Metadata } from "next";
import { Diplomata_SC, Spectral_SC, Source_Serif_4, Oswald, Allura } from 'next/font/google';
import "./globals.css";

const diplomata = Diplomata_SC({
  subsets: ['latin'], 
  weight: '400',     
  display: 'swap',
});

const spectral = Spectral_SC({
  subsets: ['latin'], 
  weight: '400',     
  display: 'swap',
});

const sourceSerif = Source_Serif_4({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
});

const oswald = Oswald({
  subsets: ['latin'],
  weight: '600',
  display: 'swap',
});

const allura = Allura({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Coffee Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  return (
    <html lang="en">
      <body className="p-4">{children}</body>
    </html>
  );
}

